### ISSUE TITLE
Your CV is great

### ISSUE THREAD

**Issue by wilfredgithuka** [mithi/resume#1]
First of all you have a great CV.

Just a question, is it better to publish in markdown (.md) or PDF?

**Comment by mithi** [comment]
Thanks! There is still much to improve. 

With git it's better if it's in markdown so you can easily see and compare the changes.
But I also upload the document on linkedin and will potentially send them to companies in the near future. That's why they're in pdf. :(

**Comment by wilfredgithuka** [comment]
Okay, I see the relevance.

Anyway keep up the good work, I have learnt alot from ur CV

#motivated

**Comment by mithi** [comment]
@wilfredgithuka thanks! There's still much to improve in my cv! Good luck to you too!
